import styles from "@/styles/Home.module.css";
import localFont from "next/font/local";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const myLink = null as unknown as string;

export default function Home() {
  const [link, setLink] = useState("/page");
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <div className={styles.ctas}>
            <button onClick={() => setLink(myLink)}>
              click me to change link. Link is now {JSON.stringify(link)}
            </button>
            <Link
              href={link}
              target="_blank"
              rel="noopener noreferrer"
              className={styles.secondary}
            >
              This is a link
            </Link>
          </div>
        </main>
      </div>
    </>
  );
}
